# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)

2.2.4


#### 3. Create a null vector of size 10 (★☆☆)

In [18]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [19]:
np.size(a)

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [20]:
np.info()

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for an array, function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is
    an `ndarray` instance, information about the array is printed.
    If `object` is a numpy object, its docstring is given. If it is
    a string, available modules are searched for matching objects.
    If None, information about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> n

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [21]:
a[5]=1
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [23]:
b=np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [27]:
np.flip(b,axis=0)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [32]:
c=np.arange(9)
c.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [34]:
d = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(d)[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [35]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [61]:
np.random.random((3,3,3))

array([[[0.04754164, 0.0672231 , 0.153342  ],
        [0.74760453, 0.23688663, 0.47082648],
        [0.98122907, 0.68983521, 0.7820954 ]],

       [[0.14540778, 0.40022   , 0.1126681 ],
        [0.27166094, 0.17798412, 0.92296866],
        [0.32777618, 0.37960667, 0.06365417]],

       [[0.23456147, 0.82329997, 0.31562081],
        [0.07414646, 0.29057364, 0.57781373],
        [0.17311964, 0.19574566, 0.37606362]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [62]:
e=np.random.random((10,10))
(np.max(e),np.min(e))

(np.float64(0.9919457216551545), np.float64(0.0018065032675442794))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [40]:
f=np.random.random((30))
np.mean(f)

np.float64(0.5565132407867446)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [42]:
g = np.zeros((5, 7), dtype=int)
g[0, :] = 1
g[-1, :] = 1
g[:, 0] = 1
g[:, -1] = 1
g

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [43]:
g = np.ones((5, 7), dtype=int)
g[0, :] = 0
g[-1, :] = 0
g[:, 0] = 0
g[:, -1] = 0
g

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

```python
nan
False
False
nan
True
False
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [74]:
matrix = np.zeros((5, 5))
for i in range(1, 5):
    matrix[i, i-1] = i
matrix

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [77]:
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1 
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [78]:
shape = (6, 7, 8)
np.unravel_index(99, shape) 

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [79]:
np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [2]:
Z = np.random.random((5,5))
Z = (Z - np.min(Z)) / (np.max(Z) - np.min(Z))
print(Z)

[[0.90744823 0.63378044 0.34355776 0.         0.64219907]
 [0.61443273 0.09294113 0.76347764 0.06527357 0.521843  ]
 [0.41080824 1.         0.82011395 0.919678   0.52932264]
 [0.5942757  0.55917939 0.91413422 0.83113226 0.97580381]
 [0.15790627 0.1191397  0.86920238 0.45421713 0.8017288 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [3]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [4]:
A = np.random.rand(5,3)
B = np.random.rand(3,2)
C = np.dot(A, B)
print(C)

[[0.48498844 0.42888569]
 [0.43082893 0.4234317 ]
 [0.36939991 0.35635787]
 [0.64760794 0.45091789]
 [0.5684879  0.41827583]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [5]:
Z = np.arange(11)
Z[(Z > 3) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
array([10])

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z <- Z
Z<Z>

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
[-9.22337204e+18]

#### 29. How to round away from zero a float array ? (★☆☆)

In [8]:
Z = np.random.uniform(-10, +10, 10)
Z_rounded = np.copysign(np.ceil(np.abs(Z)), Z)
print(Z_rounded)

[ 9. -7.  4. -3.  2. -2. -1.  8. -4. -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [9]:
A = np.array([1, 2, 3, 4])
B = np.array([3, 4, 5, 6])
common = np.intersect1d(A, B)
print(common) 

[3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [10]:
import warnings
warnings.filterwarnings('ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [12]:
import datetime
yesterday = datetime.datetime.now() - datetime.timedelta(days=1)
today = datetime.datetime.now()
tomorrow = datetime.datetime.now() + datetime.timedelta(days=1)
print(yesterday, today, tomorrow)

2025-04-21 20:08:46.801309 2025-04-22 20:08:46.801330 2025-04-23 20:08:46.801344


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [13]:
import numpy as np
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [15]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [16]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[5. 6. 0. 7. 3. 3. 3. 3. 9. 2.]
[5. 6. 0. 7. 3. 3. 3. 3. 9. 2.]
[5. 6. 0. 7. 3. 3. 3. 3. 9. 2.]
[5 6 0 7 3 3 3 3 9 2]
[5. 6. 0. 7. 3. 3. 3. 3. 9. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [17]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [18]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [19]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [20]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.04341871 0.07444013 0.09069751 0.16717331 0.16757858 0.23251646
 0.4265509  0.45352236 0.48526931 0.60113194]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [21]:
Z = np.arange(10)
np.add.reduce(Z)

np.int64(45)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [22]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [23]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [24]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.76779076 0.36587837 0.30724589 0.16043834 1.07119459 1.04655881
 0.97222559 1.22322512 0.97561601 0.78814486]
[0.35593388 1.40770061 0.95371269 1.27910825 0.4056962  0.9692861
 1.10760791 0.95111743 1.24272922 0.99980937]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [25]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.60404727 0.44163329 0.36826222 0.8559876  0.59604082 0.37433758
 0.70142439 0.         0.67337294 0.60005682]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [26]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [27]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [30]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [29]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [28]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

65


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [34]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [33]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.60568912 0.56548984 0.37321381 0.79201869 0.68721674
  0.15754727 0.65259134 0.88808021 0.18576753]
 [0.60568912 0.         0.18567589 0.97707105 0.1950592  0.10122949
  0.63055575 0.20954276 0.33981672 0.52339253]
 [0.56548984 0.18567589 0.         0.9348591  0.27281427 0.27820265
  0.5434742  0.39045238 0.32473127 0.54222987]
 [0.37321381 0.97707105 0.9348591  0.         1.16500178 1.05463658
  0.41864045 1.00164938 1.25898967 0.48717018]
 [0.79201869 0.1950592  0.27281427 1.16500178 0.         0.1669467
  0.79941647 0.32396945 0.17533656 0.71828888]
 [0.68721674 0.10122949 0.27820265 1.05463658 0.1669467  0.
  0.72379843 0.15964362 0.33907861 0.58589114]
 [0.15754727 0.63055575 0.5434742  0.41864045 0.79941647 0.72379843
  0.         0.72292158 0.86626448 0.32951641]
 [0.65259134 0.20954276 0.39045238 1.00164938 0.32396945 0.15964362
  0.72292158 0.         0.49802653 0.51602121]
 [0.88808021 0.33981672 0.32473127 1.25898967 0.17533656 0.33907861
  0.86626448 0.498026

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [31]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[63 13 41 53 67  0 64 36 95 11]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [36]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [37]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [38]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [39]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.34341494  0.2978025  -0.03283278  0.31494059 -0.35684661 -0.15378766
   0.47657842 -0.29086195 -0.39502539  0.48344782]
 [ 0.41244631 -0.47924346 -0.07558613  0.42479752  0.09010894  0.40028149
  -0.2665531  -0.31913749  0.11062369 -0.29773776]
 [ 0.03949812 -0.11247108 -0.04697161 -0.19891417 -0.41894925  0.35055375
  -0.06290311  0.35379393 -0.01777069  0.11413411]
 [ 0.18064125 -0.1740961   0.00881464 -0.32497321 -0.32835256  0.15281041
   0.20571704 -0.08213738  0.19332556  0.16825036]
 [-0.33716696  0.49605587 -0.03328014 -0.06468237  0.26909558  0.23881173
  -0.25816857  0.08892775 -0.21623873 -0.18335415]]


#### 59. How to sort an array by the nth column? (★★☆)

In [40]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 7 2]
 [6 6 1]
 [0 4 5]]
[[0 4 5]
 [6 6 1]
 [3 7 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [41]:
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [42]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5478360995468665


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [43]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [44]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [45]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[4. 1. 2. 2. 4. 3. 4. 5. 3. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [46]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [49]:
I24 = np.dot(I.astype(np.uint32),[1,256,65536])
n = len(np.unique(I24))
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [50]:
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

3


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [52]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.42184714 0.3924652  0.42961659 0.63153957 0.58046019 0.59244274
 0.52403153 0.44223152 0.5302904  0.62360069]
0    0.421847
1    0.392465
2    0.429617
3    0.631540
4    0.580460
5    0.592443
6    0.524032
7    0.442232
8    0.530290
9    0.623601
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [53]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.einsum("ij,ji->i", A, B)

array([1.31907165, 0.77185826, 1.59198744, 1.26282675, 1.39653896])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [54]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [55]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [56]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [57]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 32) ( 0, 55) ( 2, 12) ( 2, 82) (12, 82) (21, 49) (21, 58) (26, 50)
 (26, 94) (32, 45) (32, 55) (32, 96) (41, 44) (41, 51) (41, 56) (41, 99)
 (44, 56) (45, 96) (49, 58) (50, 94) (51, 99) (52, 58) (52, 97) (56, 65)
 (56, 93) (58, 97) (65, 93) (91, 91) (91, 92)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [58]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [59]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [62]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [63]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.09078948, -0.00869866, -0.92665452,  0.19925204, -0.95366151,
        0.71575183, -0.9949947 ,  0.67021633,  0.43071293, -0.21005207,
        0.01912473,  0.62848421,  0.56886039,  0.82767466, -0.30229621,
        0.89780128, -0.57943811, -0.29897106, -0.7336474 , -0.35297383,
        0.85016086,  0.7426819 ,  0.07161457, -0.89488106, -0.65384413,
        0.68729419,  0.70306403,  0.48649679,  0.82698974,  0.99404403,
       -0.78504117, -0.81590724,  0.67857035,  0.23972838, -0.69971468,
       -0.47728792,  0.62705202,  0.30845689,  0.71068805, -0.19233846,
        0.09797398,  0.8214129 , -0.96919539,  0.45666705,  0.47688309,
        0.27744611,  0.53011911, -0.891221  , -0.96655569,  0.043609  ,
       -0.07099825, -0.72809024,  0.30747881, -0.33422363, -0.06358413,
        0.27457397, -0.41114979,  0.28565629,  0.34298756,  0.12212538,
       -0.34813863,  0.68705084,  0.02323378, -0.47675596,  0.7641249 ,
       -0.71936199,  0.59470603,  0.24618685, -0.97938962, -0.63

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [64]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[3.17786615 1.54779371 6.27520476 0.65946534 4.31345285 0.56704296
 9.66072789 1.12241278 6.83340801 6.90115155]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [65]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.87056976  3.23614922  4.75404709  9.58207028 14.53149778  3.65401178
   5.85803598  6.89556569  3.92276356 11.32230024]
 [12.78628071 11.52022432  0.36424203  8.20998392  0.0754892   1.51556471
   0.23336127  4.4565411   6.87545576  3.73528116]
 [ 3.60537832  2.82238288 14.5873049   1.94495098  8.11722789 13.12593586
   5.80868557  3.11131576  6.48936538  0.11538499]
 [ 3.18507841  0.63376197 16.00029724  4.53017409  4.70591589 14.35289868
   9.09539089  6.80358757  8.22715924  3.56774029]
 [13.81818181 11.11002612  1.81311093 10.90136219  1.71731744  3.59284246
   2.59090701  1.903436    9.21713945  6.53854452]
 [ 8.83113201  7.11734977  2.87632605  7.23205828  3.5577073   1.18818743
   0.19592863  2.23935867  4.72712823  4.64354308]
 [ 3.06257618  4.34238355 12.16866696  1.50899379 11.35323541 10.88550196
   1.86649613  0.85162868  3.76740286  3.90273052]
 [ 5.94313423  7.44917057  8.17326343  0.97520892  0.02488081  6.28362173
   6.1710369   7.7451617   0.89399507  1.61020518]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [67]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [68]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [69]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [70]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 0 3]
   [3 4 0]
   [1 4 2]]

  [[0 3 2]
   [4 0 0]
   [4 2 1]]

  [[3 2 4]
   [0 0 4]
   [2 1 1]]

  [[2 4 4]
   [0 4 4]
   [1 1 2]]

  [[4 4 2]
   [4 4 4]
   [1 2 2]]

  [[4 2 3]
   [4 4 4]
   [2 2 3]]

  [[2 3 0]
   [4 4 1]
   [2 3 4]]

  [[3 0 4]
   [4 1 1]
   [3 4 0]]]


 [[[3 4 0]
   [1 4 2]
   [0 0 1]]

  [[4 0 0]
   [4 2 1]
   [0 1 2]]

  [[0 0 4]
   [2 1 1]
   [1 2 0]]

  [[0 4 4]
   [1 1 2]
   [2 0 4]]

  [[4 4 4]
   [1 2 2]
   [0 4 2]]

  [[4 4 4]
   [2 2 3]
   [4 2 4]]

  [[4 4 1]
   [2 3 4]
   [2 4 2]]

  [[4 1 1]
   [3 4 0]
   [4 2 1]]]


 [[[1 4 2]
   [0 0 1]
   [2 0 2]]

  [[4 2 1]
   [0 1 2]
   [0 2 0]]

  [[2 1 1]
   [1 2 0]
   [2 0 3]]

  [[1 1 2]
   [2 0 4]
   [0 3 2]]

  [[1 2 2]
   [0 4 2]
   [3 2 4]]

  [[2 2 3]
   [4 2 4]
   [2 4 3]]

  [[2 3 4]
   [2 4 2]
   [4 3 3]]

  [[3 4 0]
   [4 2 1]
   [3 3 3]]]


 [[[0 0 1]
   [2 0 2]
   [1 0 1]]

  [[0 1 2]
   [0 2 0]
   [0 1 3]]

  [[1 2 0]
   [2 0 3]
   [1 3 4]]

  [[2 0 4]
   [0 3 2]
   [3 4 3]]

  [[0 4 2]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [71]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8  6  8 16  5]
 [ 6  1  5 10 11]
 [ 8  5  0 42 11]
 [16 10 42  4 13]
 [ 5 11 11 13  0]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [72]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [73]:
Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [74]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [75]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [76]:

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [77]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [78]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

246 ms ± 24.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [79]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 3 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [80]:
Z = np.random.randint(0,5,(10,3))
print(Z)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 2 2]
 [4 4 3]
 [1 3 3]
 [2 2 1]
 [0 1 1]
 [3 1 0]
 [3 2 0]
 [4 0 1]
 [1 3 0]
 [4 1 1]]
[[4 4 3]
 [1 3 3]
 [2 2 1]
 [0 1 1]
 [3 1 0]
 [3 2 0]
 [4 0 1]
 [1 3 0]
 [4 1 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)